OUTPUT_DIR: "./logs/ImageNet_finetune"
MODEL:
  META_ARCHITECTURE: "Detr"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  DETR:
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 100
DATASETS:
  TRAIN: ("train_kuna_coco",)
  PROPOSAL_FILES_TRAIN: ("/opt/kuna/data/clean_vertexFull100k_S2018/vertexFull100k_S2018/vertex_coco/train_coco_dataset.json",)
  TEST: ("val_kuna_coco",)
  PROPOSAL_FILES_TEST: ("/opt/kuna/data/clean_vertexFull100k_S2018/vertexFull100k_S2018/vertex_coco/val_coco_dataset.json",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0001
  STEPS: (100000,)
  MAX_ITER: 160000 # ~200 epochs for 2x32
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (360,)
  MIN_SIZE_TEST: (360)
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (352, 352)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 3000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
